// Pre-medicine (MD and DO). Source: HPAO "Medicine" and "Application Process" pages, fetched
// 2026-09-25 (SOURCES.md). Encoded by hand. UNVERIFIED until the owner signs off.

import { HPAO_DISCLAIMER, type Track } from "../src/types.ts";
import {
  COMMITTEE_MILESTONES,
  HPAO,
  MAPPING_NOTES,
  biochem,
  calculus,
  english,
  genChem1,
  genChem2,
  introBio,
  organicChem,
  physics,
  statistics,
  upperBioLab,
} from "./common.ts";

const onMcat = { examContent: "mcat" };

export const preMed: Track = {
  id: "pre-med",
  name: "Pre-Medicine (MD and DO)",
  schools: "medical schools",
  minGrade: "C",
  minGradeNote: "HPAO: medical schools generally require a C (not a C-) in every prerequisite.",
  entry: { kind: "after-degree" },
  categories: [
    genChem1("8 Credits of Inorganic Chemistry with labs", onMcat),
    genChem2("8 Credits of Inorganic Chemistry with labs", onMcat),
    organicChem("8 Credits of Organic Chemistry with labs", onMcat),
    biochem("Biochemistry", onMcat),
    introBio("8-12 credits of Biology with labs", onMcat),
    upperBioLab("8-12 credits of Biology with labs"),
    calculus("Calculus"),
    statistics("Statistics"),
    physics("8 Credits of Physics with labs", onMcat),
    english("6 Credits of English"),
  ],
  milestones: [
    {
      id: "mcat",
      kind: "exam",
      name: "MCAT",
      detail: "Registration opens in October for January–September test dates. Plan 4–6 months of study, and finish the science courses the MCAT covers first. HPAO: your first attempt should be no later than June 30 of the year you apply.",
      start: { year: -2, month: 10 },
      due: { year: -1, month: 6, day: 30 },
    },
    {
      id: "clinical",
      kind: "experience",
      name: "Clinical experience",
      detail: "At least 10–12 months of long-term clinical experience before you apply: shadowing, scribing, EMT, medical assistant, or hospital/clinic volunteering.",
      due: { year: -1, month: 6, day: 7 },
    },
    {
      id: "service",
      kind: "experience",
      name: "Community service",
      detail: "At least 1 year (10–12 months) of long-term community service, ideally both clinical and non-clinical.",
      due: { year: -1, month: 6, day: 7 },
    },
    {
      id: "research",
      kind: "experience",
      name: "Research",
      detail: "At least 1 semester of clinical or academic research. Not required by most schools, but most successful applicants have it.",
      due: { year: -1, month: 6, day: 7 },
      optional: true,
    },
    ...COMMITTEE_MILESTONES,
    {
      id: "situational-judgement",
      kind: "exam",
      name: "Situational judgement tests (Casper, PREview)",
      detail: "Only some schools require them. HPAO recommends taking any you need by June 30.",
      due: { year: -1, month: 6, day: 30 },
      optional: true,
    },
    {
      id: "primary-application",
      kind: "application",
      name: "Primary application (AMCAS / AACOMAS)",
      detail: "AMCAS and AACOMAS open in early May. For best consideration, HPAO recommends submitting by June 7. Send transcripts after spring grades post (about May 25).",
      start: { year: -1, month: 5 },
      due: { year: -1, month: 6, day: 7 },
    },
    {
      id: "secondary-applications",
      kind: "application",
      name: "Secondary applications",
      detail: "Complete and return each school's secondary application within two weeks of receiving it (July–September).",
      start: { year: -1, month: 7 },
      due: { year: -1, month: 9, day: 30 },
    },
  ],
  disclaimer: HPAO_DISCLAIMER,
  sources: [HPAO.career("medicine"), HPAO.application, HPAO.apIb, HPAO.bioMajor, HPAO.neurPlan],
  verified: false,
  reviewNotes: [
    MAPPING_NOTES.genChem,
    MAPPING_NOTES.organic,
    MAPPING_NOTES.biochem,
    MAPPING_NOTES.introBio,
    MAPPING_NOTES.upperBio,
    MAPPING_NOTES.physics,
    MAPPING_NOTES.calculus,
    MAPPING_NOTES.statistics,
    MAPPING_NOTES.english,
    MAPPING_NOTES.grades,
    "MCAT content courses (must come before the MCAT term): general chemistry I and II, organic chemistry, biochemistry, introductory biology and physics. Psychology and sociology (also on the MCAT) are not HPAO prerequisites, so they aren't checked.",
    "Milestone dates are HPAO's 2028-cycle timeline, stored relative to the fall the student starts medical school (apply the June after junior year to start right after graduation). The owner should confirm them each cycle.",
    "HPAO's humanities/social science and school-specific requirements are not encoded (optional target-school layer, later).",
  ],
};
